--LENGUAJE DE DEFINICIÓN DE DATOS (DDL) - CREACIÓN
--DEFINICIÓN TABLA PERSONA
--CONSTRAINT CREAR O ELIMINAR UN RESTRICCIÓN
CREATE TABLE TBL_PERSONA(
    PE_ID NUMERIC NOT NULL ,--CLAVE PRIMARIA O PRIMARY KEY (NO PUEDE REPETIRSE, DEBE SER ÚNICO)
    PE_NOMBRE VARCHAR(50) NOT NULL, --CHAR VARIABLE DE 50
    PE_APELLIDO VARCHAR(70) NOT NULL,
    PE_EDAD NUMERIC NOT NULL,
    CONSTRAINT TBL_PERSONA_PK PRIMARY KEY (PE_ID)
);


--LENGUAJE DE MANIPULACIÓN DE DATOS (DML) - MANIPULACIÓN,
--INSERTAR UN REGISTRO EN LA TABLA
INSERT INTO public."TBL_PERSONA"("PE_ID","PE_NOMBRE","PE_APELLIDO","PE_EDAD") VALUES (1,'DAVID','BACILIO',20);
INSERT INTO public."TBL_PERSONA"("PE_ID","PE_NOMBRE","PE_APELLIDO","PE_EDAD") VALUES (2,'CHRISTIAN','DE LA CRUZ',21);
--CONSULTA
SELECT "PE_APELLIDO", "PE_EDAD" FROM public."TBL_PERSONA";
SELECT "PE_APELLIDO", "PE_EDAD", "PE_ID" FROM public."TBL_PERSONA";
--ACTUALIZACIÓN DE UN REGISTRO
UPDATE public."TBL_PERSONA" SET "PE_EDAD" = 16, "PE_APELLIDO"= 'X' WHERE "PE_ID" = 1;
--ELIMINACIÓN DE UN REGISTRO
DELETE FROM public."TBL_PERSONA" WHERE "PE_ID" = 1;

--CREAR UNA TABLA QUE CONTENGA TRANSACCIONES:
COLUMNAS MES,EMPLEADO,VENTAS, PRODUCTO
ENERO, JUAN, 4000, ROPA
FEBRERO, LUIS, 6000, PERFUME

APP: 1 INSERTAR, 2 SELECCIONAR, 3 ACTUALIZAR, 4 ELIMINAR

