DROP TABLE IF EXISTS TBL_PERSONA;
DROP SEQUENCE IF EXISTS TBL_PERSONA_SEQ;
CREATE TABLE IF NOT EXISTS TBL_PERSONA
(
    PE_ID       NUMERIC     NOT NULL,
    PE_NOMBRE   VARCHAR(50) NOT NULL,
    PE_APELLIDO VARCHAR(70) NOT NULL,
    PE_EDAD     NUMERIC     NOT NULL,
    PE_DNI      VARCHAR(8)  NOT NULL,
    CONSTRAINT TBL_PERSONA_PK PRIMARY KEY (PE_ID)
);

CREATE SEQUENCE IF NOT EXISTS TBL_PERSONA_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 100
    START 1;

INSERT INTO TBL_PERSONA(PE_ID, PE_NOMBRE, PE_APELLIDO, PE_EDAD, PE_DNI)
VALUES (nextval('TBL_PERSONA_SEQ'), 'DAVID', 'BACILIO', 20, '44910178');

SELECT PE_ID,PE_NOMBRE,PE_APELLIDO,PE_EDAD,PE_DNI FROM TBL_PERSONA;
SELECT * FROM TBL_PERSONA where PE_ID = 1;

UPDATE TBL_PERSONA SET PE_NOMBRE=?, PE_APELLIDO=?, PE_EDAD=?, PE_DNI=? WHERE PE_ID = ?;

DELETE FROM TBL_PERSONA WHERE PE_ID = ?;